# Your Project Name
spring.application.name=file-sharing-system

# Database Connection (The "Bridge")
spring.datasource.url=jdbc:mysql://localhost:3306/filesharing_db
spring.datasource.username=root
spring.datasource.password=123456

# Auto-Setup (This creates tables automatically from your Java code)
spring.jpa.hibernate.ddl-auto=update
# Fix: Added .jpa. to the property
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.frontend.base-url=http://localhost:5173
